version: '3'

services:
  mysqldb:
    build:
      context: ./mysql-service
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql-service/data:/var/lib/mysql

  http:
    build:
      context: ./http-service
      dockerfile: Dockerfile
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - TCP_HOST=tcp
      - TCP_PORT=${TCP_PORT}
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    depends_on:
      - tcp

  tcp:
    build:
      context: ./tcp-service
      dockerfile: Dockerfile
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=mysqldb
      - TCP_PORT=${TCP_PORT}
    depends_on:
      - mysqldb